### PR TITLE
Smooth drags

### PR DESCRIPTION
**Pull request by CRojo**
I smoothed the dragging. And added a missing break =) 

I also did a bit more cleanup.

### CODE REVIEW

**Comment by CRojo** [comment]
One issue with having a method like that is that it wouldn't solve the problem of getting the edge points to 'redirect' themselves to the new vertex position. I'd still need some per-edge conditional logic in renderEdge. I can simplify it a bit to not require passing an object, but rather just the position offset, similar to how renderVertex is currently. We can simplify it more by removing all drag-state except the boolean indicating a drag-state. That would get rid of the draggingFrom/draggingTo state and just directly update the selected vertex position with each new mouse move. Any objections to that?

**Comment by ericmick** [comment]
In renderEdge, just use the same method "getPoint" twice to get the locations of the two vertices + dragging.  You still need draggingFrom in order to calculate `p[t] = p[0] + m[t] - m[0]` or "the point where the vertex is now is equal to where it was, plus where the mouse is, minus where the mouse was when the drag started."

**Comment by ericmick** [comment]
I'll pull your change modify so you can see what I mean.

**Comment by CRojo** [comment]
Just a thought. This would let you get rid of dragTo/dragFrom:
if (dragging) {
  draggedVertex.p = untransform(mouse.p);
}

Only issue with that is that it'd recenter every time you click it. If you do want to keep the state-based dragging, you'd only need to compute the delta from the last registered mouse-drag position to the current one in a continuous drag, you wouldn't need to keep the origin where the drag started. 

You're killing me with these one-character variable names.

**Comment by ericmick** [comment]
I've merged and added my change.  Long variable names are for Java.  :-P

**Comment by CRojo** [comment]
Yay! I like it

**Pull request merged**
